theme: minima
title: Mine blog
author: CCatrose
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I discovert a new world for me. have a nice day!!!!!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
